### PR TITLE
New plugin architecture and other useful configurations

### PR DESCRIPTION
**Pull request by deadratfink**
**New feature implementations:**

- New plugin architecture with:
  - Creation of custom operator plugins.
  - Overwriting of known (standard) operators.
  - Usage of predefined plugins:
    - Is-Any: Overwrite of `=in=` (mapped to PostgreSQL's `= ANY(...)`).
    - Is-Not-All: Overwrite of `=out=` (mapped to PostgreSQL's `<> ALL(...)`).
    - Is-Null: `=null=[true | false]` => `IS [ NOT ] null`
    - Is-Empty: `=empty=[true | false]` => `[ = | <>] ''`.
    - Is-Null-Or-Empty: `=null_or_empty=[true | false]` => `(... IS [ NOT ] null OR ... [ = | <>]  '')`.
  - Exported new function `formatKeyword(keyword: string, keywordsLowerCase = false)` to be usable in plugins.
  - Exported existing function `formatSelector(context: SqlContext, selector: string)` to be usable in plugins.
  - Exported existing function `formatValue({ allowArray, ast }: { ast: ComparisonNode; allowArray?: boolean }, config: StaticQueryConfig)` to be usable in plugins.
- Extended configuration:
  - Plugins from above (`plugins`, default: `undefined`).
  - SQL cosmetics:
    - SQL keyword lower-case and UPPER-case configuration (default: UPPER).
      - **NOTE: Since this was somehow a mixed style before, this is unified to upper-case now and therefore is not fully "backwards compatible".**
    - Plain SQL operators with SPACE around or not (`detachedOperators`, default: `false`).
    - Prefix configuration for `WHERE` (`whereKeywordPrefix`, default: `" "`).

**Internals:**

- Added `.editorconfig`
- Some minor code adaptions/refactorings.
- Some unit tests added.
- Some js-doc added.
- Added new test-coverage script: `npm run test:coverage`.
- `coverage` folder ignored from Git.
- Added a `Makefile` for convenience (optional usage, requires UNIX-like environment).

### CODE REVIEW

**Comment by deadratfink** [comment]
Hi, a PR from my side. Would appreciate if we can push the changes back to your origin repo, instead of maintaining a fork. What do you think about this? Of course, I need to make some adaptions before merge. Please see also README.md for a description of the new plugin feature.

The motivation behind it was that we needed the custom/overwriting operators in our projects. I made some beta releases of the fork already and put it into our project and it works quite nice.

**Comment by massfords** [comment]
@deadratfink Thanks for the PR and taking an interest in the lib.

It looks like you put a lot into this. I'll have some time to review this closely in a couple of days. I'm open to merging it after taking a closer look.

**Comment by deadratfink** [comment]
Good morning @massfords, thanks a lot for your interests in it. Sorry, yeah it is quite lot, but we needed these features asap. So, I had to hurry up a bit. I will adapt the libs name to the original one this morning. Anyway, I guess you will find  some issues while reviewing ;-)

**Comment by deadratfink** [comment]
@massfords Have fixed some found issues and prepared name and version for a merge.

**Comment by massfords** [comment]
I've added you as a collaborator so you should be able to run the CI/CD. It's failing likely due to an issue with an old version of Node but I didn't take a close look. 

- [x] get the ci/cd passing, likely by dropping the old versions of Node and running on more modern ones
- [x] add something to live-db.it.ts to exercise the plugins. This is a live run against a real Postgres (albeit in a testcontainer docker image) and provides confidence that the queries work as expected

**Comment by deadratfink** [comment]
OK, will a look on that later, have to finish some work for customers at the moment.

**Comment by deadratfink** [comment]
I got CI/CD passing, I updated it Node 15, but actually that should not be the issue when failing, it was the `"lockfileVersion": 3` committed from my side (I installed with Node 18). I reverted to the `"lockfileVersion": 2` and it passed afterwards.

Anyway, Actions should be updated to run at least Node 16 I would suggest.

Regarding live-db: I can add some stuff later, maybe tomorrow. I will notify you when its done.

**Comment by deadratfink** [comment]
Hi @massfords, I added also live-db tests for plugins. I did also some bugfixing from their outcome. So, it was a good point to do this ;-) 

From my side it is ready to review now.

**Review by massfords — APPROVED** [review]
Looks good. Thanks for all of the work.

There are a couple of minor JSDoc issues but I'll fix them in a separate PR

**Pull request merged**
